bloom/order/urls.py
from django.urls import path
from . import views
app_name = "order"
urlpatterns = [
    path("order/overview/", views.OrderOverviewPage.as_view(), name="order-overview"),
    path("order/<uuid>/purchase-confirmed/", views.OrderSuccessPage.as_view(), name="order-success"),
    path("order/<uuid>/purchase-canceled/", views.OrderCanceledPage.as_view(), name="order-canceled"),
    path("order/hooks/", views.OrderHooksPage.as_view(), name="order-hooks"),
    path("account/hooks/", views.AccountHooksPage.as_view(), name="account-hooks"),
    path("shipstation/order-hooks/", views.ShipStationHooksPage.as_view(), name="ship-hooks"),
]

bloom/shop/urls.py
from django.urls import path
from . import views
app_name = "shop"
urlpatterns = [
    path("customers/redact/", views.CustomersRedactView.as_view(), name="customers-redact"),
    path("shop/redact/", views.ShopRedactView.as_view(), name="shop-redact"),
    path("customers/data_request/", views.CustomersDataRequestView.as_view(), name="customers-data-request"),
    path("shop/<slug:slug>/", views.ShopDetails.as_view(), name="shop-details"),
    path("my-shops/", views.MyShopsView.as_view(), name="my-shops"),
    path("my-purchase/", views.MyPurchaseView.as_view(), name="my-purchase"),
    path("my-collections/", views.MyCollectionsView.as_view(), name="my-collections"),
    path("search/", views.SearchView.as_view(), name="search-page"),
    path("spreadsheet/callback/", views.SpreadsheetCallback.as_view(), name="spreadsheet-callback"),
    path("business/products/", views.ProductsPage.as_view(), name="products_page"),
    path("business/my-orders/", views.MyOrderPage.as_view(), name="orders_page"),
    path("business/product/upload/", views.ProductUpload.as_view(), name="product_add_page"),
    path("business/product/<uuid>/update/", views.ProductUpdate.as_view(), name="product_update_page"),
    path("business/products/shopify/import/", views.ImportProductsShopifyView.as_view(), name="shopify-import-products"),
    path("business/products/file/import/", views.ImportProductsFileView.as_view(), name="file-import-products"),
    path("business/products/wordpress/import/", views.ImportProductsWordpressView.as_view(),
         name="wordpress-import-products"),
    path("business/google-merchant/upload/", views.ThirdPartyProductUpoadView.as_view(), name="google-merchant-upload"),
]

bloom/users/urls.py
from django.urls import path

from bloom.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    StripConnectView,
    StripAccountRefreshView, StripeSettingView, ShopifySettingView, ShopifyCallbackView, ShopInformation,
    WordpressSettingView
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("details/", view=user_detail_view, name="detail"),
    path("shop/", view=ShopInformation.as_view(), name="shop"),
    path("stripe/connect/", view=StripConnectView.as_view(), name="stripe_connect"),
    path("stripe/refresh/", view=StripAccountRefreshView.as_view(), name="stripe_refresh"),
    path("stripe-integration/", view=StripeSettingView.as_view(), name="stripe-integration"),
    path("shopify-integration/", view=ShopifySettingView.as_view(), name="shopify-integration"),
    path("auth/shopify/callback/", view=ShopifyCallbackView.as_view(), name="shopify-callback"),
    path("wordpress-integration/", view=WordpressSettingView.as_view(), name="wordpress-integration"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from bloom.shop.views import HomePage, ProductDetails

urlpatterns = [
    path("", HomePage.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("bloom.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("order.urls"), name='order'),
    path("", include("shop.urls"), name='shop'),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("<slug:shop_slug>/product/<slug:slug>/", ProductDetails.as_view(), name="product-details"),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bloom/forms.py
from django import forms

from bloom.shop.models import Shop


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ['name', 'logo', 'business_address', 'business_phone', 'store_type']

bloom/analytics/api/views.py
import datetime
import json

from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.db.models.aggregates import Sum, Count, Avg
from django.db.models.expressions import F, OuterRef, Subquery, Value
from django.db.models.functions import Trunc, ExtractWeek, Concat, ExtractYear, ExtractMonth
from django.utils.dateformat import format
from rest_framework import status
from rest_framework.generics import CreateAPIView, get_object_or_404, ListAPIView
from rest_framework.response import Response
from rest_framework.views import APIView

from bloom.analytics.api.serializers import StorefrontViewSerializer, ProductViewSerializer
from bloom.analytics.models import StorefrontView, ProductView, ProductAddedToCart
from bloom.order.models import Order, OrderItem
from bloom.shop.api.serializers import ProductModelSimpleSerializer
from bloom.shop.models import Shop, Product


class StorefrontViewAPI(CreateAPIView):
    serializer_class = StorefrontViewSerializer
    permission_classes = []

    def perform_create(self, serializer):
        shop = get_object_or_404(Shop, uuid=self.kwargs['uuid'])
        obj, created = StorefrontView.objects.get_or_create(shop=shop,
                                                            viewed_date=datetime.date.today())
        StorefrontView.objects.filter(id=obj.id).update(count=F('count') + 1)
        obj.refresh_from_db()
        return obj


class ProductViewAPI(CreateAPIView):
    serializer_class = ProductViewSerializer
    permission_classes = []

    def perform_create(self, serializer):
        product = get_object_or_404(Product, uuid=self.kwargs['uuid'])
        channel = self.request.data['channel']
        obj, created = ProductView.objects.get_or_create(product=product,
                                                         viewed_date=datetime.date.today(),
                                                         channel=channel)
        ProductView.objects.filter(id=obj.id).update(count=F('count') + 1)
        obj.refresh_from_db()
        return obj


def product_added_to_cart_log(product):
    obj = ProductAddedToCart.objects.get_or_create(product=product,
                                                   added_date=datetime.date.today())[0]

    ProductAddedToCart.objects.filter(id=obj.id).update(count=F('count') + 1)


class StorefrontViewData(APIView):

    def get(self, request, *args, **kwargs):
        shop = request.user.get_shop()

        if request.GET.get('type') == 'month':
            data = self.get_month_data(shop)
        if request.GET.get('type') == 'by_week':
            data = self.get_data_by_week(shop)
        elif request.GET.get('type') == 'by_month':
            data = self.get_data_by_month(shop)
        else:
            data = self.get_data_by_day(shop)

        return Response(data=data, status=status.HTTP_200_OK)

    def get_month_data(self, shop):
        this_month = datetime.date.today()
        last_month = this_month - relativedelta(months=1)

        kwargs = {
            'viewed_date__month': this_month.month,
            'created_at__year': this_month.year,
        }
        this_month_count = StorefrontView.objects.filter(shop=shop,
                                                         viewed_date__month=this_month.month,
                                                         viewed_date__year=this_month.year) \
                               .aggregate(this_month_count=Sum('count'))['this_month_count'] or 0
        last_month_count = StorefrontView.objects.filter(shop=shop,
                                                         viewed_date__month=last_month.month,
                                                         viewed_date__year=last_month.year) \
                               .aggregate(last_month_count=Sum('count'))['last_month_count'] or 0

        if settings.ENABLE_DUMMY_DATA:
            return {
                'this_month': 150,
                'last_month': 88
            }
        return {
            'this_month': this_month_count,
            'last_month': last_month_count
        }

    def get_data_by_day(self, shop):
        objs = StorefrontView.objects.filter(shop=shop) \
            .annotate(total_view=F('count')) \
            .values('viewed_date', 'total_view')

        if settings.ENABLE_DUMMY_DATA:
            data = [{"viewed_date": "2021-02-10", "total_view": 9}, {"viewed_date": "2021-02-10", "total_view": 7},
                    {"viewed_date": "2021-02-10", "total_view": 4}, {"viewed_date": "2021-02-09", "total_view": 1},
                    {"viewed_date": "2021-02-17", "total_view": 1}]
            today = datetime.date.today()
            count = 0
            for i in range(len(data), 0, -1):
                data[count]['viewed_date'] = format("Y-m-d", today - relativedelta(days=i))
                count += 1
            return data

        return list(objs)

    def get_data_by_week(self, shop):
        objs = StorefrontView.objects.filter(shop=shop) \
            .annotate(
                day_year=ExtractYear('viewed_date'),
                day_week=ExtractWeek('viewed_date')) \
            .values('day_year', 'day_week') \
            .annotate(total_view=Sum("count")) \
            .values('day_year', 'day_week', 'total_view').order_by('day_year', 'day_week')

        if settings.ENABLE_DUMMY_DATA:
            data = [{"day_year": "2021-02-10", "total_view": 9}, {"day_year": "2021-02-10", "total_view": 7},
                    {"day_year": "2021-02-10", "total_view": 4}, {"day_year": "2021-02-09", "total_view": 1},
                    {"day_year": "2021-02-17", "total_view": 1}]
            today = datetime.date.today()
            count = 0
            for i in range(len(data), 0, -1):
                day = today - relativedelta(weeks=i)
                data[count]['day_year'] = day.year
                data[count]['day_week'] = day.isocalendar()[1]
                count += 1
            return data

        return list(objs)

    def get_data_by_month(self, shop):
        objs = StorefrontView.objects.filter(shop=shop) \
            .annotate(
                day_year=ExtractYear('viewed_date'),
                day_month=ExtractMonth('viewed_date')) \
            .values('day_year', 'day_month') \
            .annotate(total_view=Sum("count")) \
            .values('day_year', 'day_month', 'total_view').order_by('day_year', 'day_month')

        if settings.ENABLE_DUMMY_DATA:
            data = [{"day_year": "2021-02-10", "total_view": 9}, {"day_year": "2021-02-10", "total_view": 7},
                    {"day_year": "2021-02-10", "total_view": 4}, {"day_year": "2021-02-09", "total_view": 1},
                    {"day_year": "2021-02-17", "total_view": 1}]
            today = datetime.date.today()
            count = 0
            for i in range(len(data), 0, -1):
                day = today - relativedelta(months=i)
                data[count]['day_year'] = day.year
                data[count]['day_month'] = day.month
                count += 1
            return data

        return list(objs)


class ProductViewData(APIView):

    def get(self, request, *args, **kwargs):
        shop = request.user.get_shop()

        if request.GET.get('type') == 'month':
            data = self.get_month_data(shop)
        if request.GET.get('type') == 'by_week':
            data = self.get_data_by_week(shop)
        elif request.GET.get('type') == 'by_month':
            data = self.get_data_by_month(shop)
        else:
            data = self.get_data_by_day(shop)

        return Response(data=data, status=status.HTTP_200_OK)

    def get_month_data(self, shop):
        this_month = datetime.date.today()
        last_month = this_month - relativedelta(months=1)

        kwargs = {
            'viewed_date__month': this_month.month,
            'created_at__year': this_month.year,
        }
        this_month_count = ProductView.objects.filter(
            product__shop=shop,
            viewed_date__month=this_month.month,
            viewed_date__year=this_month.year) \
                               .aggregate(this_month_count=Sum('count'))['this_month_count'] or 0
        last_month_count = ProductView.objects.filter(product__shop=shop,
                                                      viewed_date__month=last_month.month,
                                                      viewed_date__year=last_month.year) \
                               .aggregate(last_month_count=Sum('count'))['last_month_count'] or 0

        if settings.ENABLE_DUMMY_DATA:
            return {
                'this_month': 210,
                'last_month': 110
            }

        return {
            'this_month': this_month_count,
            'last_month': last_month_count
        }

    def get_data_by_day(self, shop):
        objs = ProductView.objects.filter(
                product__shop=shop).values('viewed_date') \
            .annotate(total_view=Sum('count')) \
            .values('viewed_date', 'total_view')

        if settings.ENABLE_DUMMY_DATA:
            data = [{"viewed_date": "2021-02-11", "total_view": 5}, {"viewed_date": "2021-02-12", "total_view": 3},
                    {"viewed_date": "2021-02-10", "total_view": 6}, {"viewed_date": "2021-02-09", "total_view": 2}]
            today = datetime.date.today()
            count = 0
            for i in range(len(data), 0, -1):
                data[count]['viewed_date'] = format("Y-m-d", today - relativedelta(days=i))
                count += 1
            return data

        return list(objs)

    def get_data_by_week(self, shop):
        objs = ProductView.objects.filter(
                product__shop=shop) \
            .annotate(
                day_year=ExtractYear('viewed_date'),
                day_week=ExtractWeek('viewed_date')) \
            .values('day_year', 'day_week') \

bloom/analytics/views.py
from django.shortcuts import render

# Create your views here.

bloom/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.generics import CreateAPIView
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin, CreateModelMixin
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer, ShopperSerializer, VendorSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)


class ShopperSignUpAPIView(CreateAPIView):
    serializer_class = ShopperSerializer
    permission_classes = []


class VendorSignUpAPIView(CreateAPIView):
    serializer_class = VendorSerializer
    permission_classes = []


class SignUpInitialAPIView(APIView):
    permission_classes = []

    def get(self, request, *args, **kwargs):
        request.session['role'] = request.GET.get('role')
        return Response(status=status.HTTP_200_OK)

bloom/templates/base.html
{% extends "master_base.html" %}
{% load static i18n %}

{% block main %}
  <div id="app">
    <div class="">
      <nav class="navbar navbar-expand-md navbar-light">
        <div class="container">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" style="max-height: 30px"></a>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="w-100">
              <div class="w-50 mx-auto">
                <search-bar></search-bar>
              </div>
            </div>

            <ul class="navbar-nav flex-shrink-1">
              {% if request.user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle user-avatar d-flex align-items-center" href="javascript:void(0)" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <avatar username="{{ user.username }}" :size="25"></avatar>
                  <span style="font-size: 10px; margin: 0 10px;line-height: 10px">{{ user.first_name }}<br/> {{ user.last_name }}</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'users:detail' %}">Settings</a>
                  <a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </div>
              </li>
              {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link nowrap" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link nowrap" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
              {% endif %}
              <li class="d-flex align-items-center">
                <cart-widget class="nowrap" media-url="{{ MEDIA_URL }}"></cart-widget>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">
      {% if messages %}
          {% for message in messages %}
              <div class="alert mt-3 {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}
    </div>

    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

bloom/templates/business_base.html
{% extends "master_base.html" %}
{% load static i18n %}

{% block main %}
  <div id="app">
    <div class="d-flex business">
      <div class="b-side-menu">
        <div class="d-flex justify-content-center align-items-center" style="height: 90px">
          <a href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}"></a>
        </div>

        <ul class="menu-items">
          <li {% if page == 'dashboard' %}class="active"{% endif %}>
            <a href="{% url 'home' %}"> <i class="bl-icon bl-dashboard"></i>Dashboard</a>
          </li>
          <li {% if page == 'my_order' %}class="active"{% endif %}>
            <a href="{% url 'shop:orders_page' %}"> <i class="bl-icon bl-order"></i>Orders</a>
          </li>
{#          <li>#}
{#            <a href="{% url 'home' %}"> <i class="bl-icon bl-shipping"></i>Shipping & Returns</a>#}
{#          </li>#}
          <li {% if page == 'products' %}class="active"{% endif %}>
            <a href="{% url 'shop:products_page' %}"> <i class="bl-icon bl-product"></i>Products</a>
          </li>
{#          <li>#}
{#            <a href="{% url 'home' %}"> <i class="bl-icon bl-customer"></i>Customer</a>#}
{#          </li>#}
{#          <li>#}
{#            <a href="{% url 'home' %}"> <i class="bl-icon bl-invoice"></i>Invoice</a>#}
{#          </li>#}
{#          <li>#}
{#            <a href="{% url 'home' %}"> <i class="bl-icon bl-store-setting"></i>Store Settings</a>#}
{#          </li>#}
          <li>
            <a href="{% url 'account_logout' %}"> <i class="bl-icon bl-logout"></i>Log Out</a>
          </li>
        </ul>
      </div>
      <div class="flex-grow-1 h-100" style="min-height: 700px">
        <nav class="navbar navbar-expand-md navbar-light">
        <div class="container">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="w-100">
              <div class="w-50">
                <form method="get" action="/search/" class="mb-0 position-relative">
                  <img src="{% static 'images/icons/search.png' %}" style="position: absolute;top: 12px;left: 5px">
                  <input type="search" name="query" class="form-control search-input" placeholder="Search...">
                </form>
              </div>
            </div>

            <ul class="navbar-nav flex-shrink-1">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a href="javascript:void(0)" class="nav-link mr-3"><i class="bl-notification"></i></a>
              </li>
              <li class="nav-item">
                <a href="javascript:void(0)" class="nav-link mr-3"><i class="bl-msg"></i></a>
              </li>
              <li class="nav-item dropdown">
                <a style="color: #646464" class="nav-link dropdown-toggle mr-3" href="#" id="navbarScrollingDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                  English
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                  <li><a class="dropdown-item" href="#">French</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown vertical-line">
                <a class="nav-link dropdown-toggle user-avatar d-flex align-items-center" href="javascript:void(0)" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <div class="ml-3" style="height: 48px;width: 48px">
                  <avatar username="{{ user.username }}" :size="48"></avatar>
                  </div>
                  <div class="d-flex align-items-center ml-3">
                    <div>
                      <p class="userName mb-0">{{ user.first_name }} {{ user.last_name }}</p>
                      <p class="rolename mb-0">Admin</p>
                    </div>
                  </div>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'users:detail' %}">Settings</a>
                  <a class="dropdown-item" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
                </div>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

        <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert mt-3 {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
            {% endfor %}
        {% endif %}
      </div>

      {% block content %}
      {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

bloom/templates/master_base.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Bloom{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="OmkXjFtAS9LG66_F8Y1eS433fOvq-Hi-GB-B2zhbqwo" />

    {% block meta %}
    <meta name=”robots” content="index, follow">
    <meta name="description" content="This is an ecommerce project">
    <meta property="og:title" content="Bloom">
    <meta property="og:description" content="This is an ecomerce project">
    <meta property="og:image" content="">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    {% endblock %}

    <meta name="author" content="Bloom">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@400;700&display=swap" rel="stylesheet">

    {% block css %}
    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css file app %}
      <link href="{% static 'libs/bloomLib.css' %}" rel="stylesheet">
      <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endcompress %}
    {% endblock %}

  </head>

  <body>
    {% block signup %}
    {% endblock %}

    {% block main %}
    {% endblock %}

    {% csrf_token %}
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
      <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->
      <script src="{% static 'libs/bloomLib.umd.js' %}"></script>
      {% compress js file app %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}

    {% block main_vue %}
    {% endblock %}

    {% block extra_js %}
    {% endblock %}
  </body>
</html>

bloom/templates/signup_base.html
{% extends "master_base.html" %}
{% load static i18n %}

{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}

{% block signup %}
  <div id="app">
    {% block nav %}
    <div class="">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" style="max-height: 30px"></a>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    {% endblock %}

    <div class="signup">
      {% block content %}
      {% endblock content %}
    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}
  </div>
{% endblock %}