bloom/order/urls.py
from django.urls import path
from . import views
app_name = "order"
urlpatterns = [
    path("order/overview/", views.OrderOverviewPage.as_view(), name="order-overview"),
    path("order/<uuid>/purchase-confirmed/", views.OrderSuccessPage.as_view(), name="order-success"),
    path("order/<uuid>/purchase-canceled/", views.OrderCanceledPage.as_view(), name="order-canceled"),
    path("order/hooks/", views.OrderHooksPage.as_view(), name="order-hooks"),
    path("account/hooks/", views.AccountHooksPage.as_view(), name="account-hooks"),
    path("shipstation/order-hooks/", views.ShipStationHooksPage.as_view(), name="ship-hooks"),
]

bloom/shop/urls.py
from django.urls import path
from . import views
app_name = "shop"
urlpatterns = [
    path("customers/redact/", views.CustomersRedactView.as_view(), name="customers-redact"),
    path("shop/redact/", views.ShopRedactView.as_view(), name="shop-redact"),
    path("customers/data_request/", views.CustomersDataRequestView.as_view(), name="customers-data-request"),
    path("shop/<slug:slug>/", views.ShopDetails.as_view(), name="shop-details"),
    path("my-shops/", views.MyShopsView.as_view(), name="my-shops"),
    path("my-purchase/", views.MyPurchaseView.as_view(), name="my-purchase"),
    path("my-collections/", views.MyCollectionsView.as_view(), name="my-collections"),
    path("search/", views.SearchView.as_view(), name="search-page"),
    path("spreadsheet/callback/", views.SpreadsheetCallback.as_view(), name="spreadsheet-callback"),
    path("business/products/", views.ProductsPage.as_view(), name="products_page"),
    path("business/my-orders/", views.MyOrderPage.as_view(), name="orders_page"),
    path("business/product/upload/", views.ProductUpload.as_view(), name="product_add_page"),
    path("business/product/<uuid>/update/", views.ProductUpdate.as_view(), name="product_update_page"),
    path("business/products/shopify/import/", views.ImportProductsShopifyView.as_view(), name="shopify-import-products"),
    path("business/products/file/import/", views.ImportProductsFileView.as_view(), name="file-import-products"),
    path("business/products/wordpress/import/", views.ImportProductsWordpressView.as_view(),
         name="wordpress-import-products"),
    path("business/google-merchant/upload/", views.ThirdPartyProductUpoadView.as_view(), name="google-merchant-upload"),
]

bloom/users/urls.py
from django.urls import path

from bloom.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    StripConnectView,
    StripAccountRefreshView, StripeSettingView, ShopifySettingView, ShopifyCallbackView, ShopInformation,
    WordpressSettingView
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("details/", view=user_detail_view, name="detail"),
    path("shop/", view=ShopInformation.as_view(), name="shop"),
    path("stripe/connect/", view=StripConnectView.as_view(), name="stripe_connect"),
    path("stripe/refresh/", view=StripAccountRefreshView.as_view(), name="stripe_refresh"),
    path("stripe-integration/", view=StripeSettingView.as_view(), name="stripe-integration"),
    path("shopify-integration/", view=ShopifySettingView.as_view(), name="shopify-integration"),
    path("auth/shopify/callback/", view=ShopifyCallbackView.as_view(), name="shopify-callback"),
    path("wordpress-integration/", view=WordpressSettingView.as_view(), name="wordpress-integration"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from bloom.shop.views import HomePage, ProductDetails

urlpatterns = [
    path("", HomePage.as_view(), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("bloom.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("order.urls"), name='order'),
    path("", include("shop.urls"), name='shop'),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("<slug:shop_slug>/product/<slug:slug>/", ProductDetails.as_view(), name="product-details"),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bloom/forms.py
from django import forms

from bloom.shop.models import Shop


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ['name', 'logo', 'business_address', 'business_phone', 'store_type']

bloom/analytics/api/views.py
import datetime
import json

from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.db.models.aggregates import Sum, Count, Avg
from django.db.models.expressions import F, OuterRef, Subquery, Value
from django.db.models.functions import Trunc, ExtractWeek, Concat, ExtractYear, ExtractMonth
from django.utils.dateformat import format
from rest_framework import status
from rest_framework.generics import CreateAPIView, get_object_or_404, ListAPIView
from rest_framework.response import Response
from rest_framework.views import APIView

from bloom.analytics.api.serializers import StorefrontViewSerializer, ProductViewSerializer
from bloom.analytics.models import StorefrontView, ProductView, ProductAddedToCart
from bloom.order.models import Order, OrderItem
from bloom.shop.api.serializers import ProductModelSimpleSerializer
from bloom.shop.models import Shop, Product


class StorefrontViewAPI(CreateAPIView):
    serializer_class = StorefrontViewSerializer
    permission_classes = []

    def perform_create(self, serializer):
        shop = get_object_or_404(Shop, uuid=self.kwargs['uuid'])
        obj, created = StorefrontView.objects.get_or_create(shop=shop,
                                                            viewed_date=datetime.date.today())
        StorefrontView.objects.filter(id=obj.id).update(count=F('count') + 1)
        obj.refresh_from_db()
        return obj


class ProductViewAPI(CreateAPIView):
    serializer_class = ProductViewSerializer
    permission_classes = []

    def perform_create(self, serializer):
        product = get_object_or_404(Product, uuid=self.kwargs['uuid'])
        channel = self.request.data['channel']
        obj, created = ProductView.objects.get_or_create(product=product,
                                                         viewed_date=datetime.date.today(),
                                                         channel=channel)
        ProductView.objects.filter(id=obj.id).update(count=F('count') + 1)
        obj.refresh_from_db()
        return obj


def product_added_to_cart_log(product):
    obj = ProductAddedToCart.objects.get_or_create(product=product,
                                                   added_date=datetime.date.today())[0]

    ProductAddedToCart.objects.filter(id=obj.id).update(count=F('count') + 1)


class StorefrontViewData(APIView):

    def get(self, request, *args, **kwargs):
        shop = request.user.get_shop()

        if request.GET.get('type') == 'month':
            data = self.get_month_data(shop)
        if request.GET.get('type') == 'by_week':
            data = self.get_data_by_week(shop)
        elif request.GET.get('type') == 'by_month':
            data = self.get_data_by_month(shop)
        else:
            data = self.get_data_by_day(shop)

        return Response(data=data, status=status.HTTP_200_OK)

    def get_month_data(self, shop):
        this_month = datetime.date.today()
        last_month = this_month - relativedelta(months=1)

        kwargs = {
            'viewed_date__month': this_month.month,
            'created_at__year': this_month.year,
        }
        this_month_count = StorefrontView.objects.filter(shop=shop,
                                                         viewed_date__month=this_month.month,
                                                         viewed_date__year=this_month.year) \
                               .aggregate(this_month_count=Sum('count'))['this_month_count'] or 0
        last_month_count = StorefrontView.objects.filter(shop=shop,
                                                         viewed_date__month=last_month.month,
                                                         viewed_date__year=last_month.year) \
                               .aggregate(last_month_count=Sum('count'))['last_month_count'] or 0

        if settings.ENABLE_DUMMY_DATA:
            return {
                'this_month': 150,
                'last_month': 88
            }
        return {
            'this_month': this_month_count,
            'last_month': last_month_count
        }

    def get_data_by_day(self, shop):
        objs = StorefrontView.objects.filter(shop=shop) \
            .annotate(total_view=F('count')) \
            .values('viewed_date', 'total_view')

        if settings.ENABLE_DUMMY_DATA:
            data = [{"viewed_date": "2021-02-10", "total_view": 9}, {"viewed_date": "2021-02-10", "total_view": 7},
                    {"viewed_date": "2021-02-10", "total_view": 4}, {"viewed_date": "2021-02-09", "total_view": 1},
                    {"viewed_date": "2021-02-17", "total_view": 1}]
            today = datetime.date.today()
            count = 0
            for i in range(len(data), 0, -1):
                data[count]['viewed_date'] = format("Y-m-d", today - relativedelta(days=i))
                count += 1
            return data

        return list(objs)

    def get_data_by_week(self, shop):
        objs = StorefrontView.objects.filter(shop=shop) \
            .annotate(
                day_year=ExtractYear('viewed_date'),
                day_week=ExtractWeek('viewed_date')) \
            .values('day_year', 'day_week') \
            .annotate(total_view=Sum("count")) \
            .values('day_year', 'day_week', 'total_view').order_by('day_year', 'day_week')

        if settings.ENABLE_DUMMY_DATA:
            data = [{"day_year": "2021-02-10", "total_view": 9}, {"day_year": "2021-02-10", "total_view": 7},
                    {"day_year": "2021-02-10", "total_view": 4}, {"day_year": "2021-02-09", "total_view": 1},
                    {"day_year": "2021-02-17", "total_view": 1}]
            today = datetime.date.today()
            count = 0
            for i in range(len(data), 0, -1):
                day = today - relativedelta(weeks=i)
                data[count]['day_year'] = day.year
                data[count]['day_week'] = day.isocalendar()[1]
                count += 1
            return data

        return list(objs)

    def get_data_by_month(self, shop):
        objs = StorefrontView.objects.filter(shop=shop) \
            .annotate(
                day_year=ExtractYear('viewed_date'),
                day_month=ExtractMonth('viewed_date')) \
            .values('day_year', 'day_month') \
            .annotate(total_view=Sum("count")) \
            .values('day_year', 'day_month', 'total_view').order_by('day_year', 'day_month')

        if settings.ENABLE_DUMMY_DATA:
            data = [{"day_year": "2021-02-10", "total_view": 9}, {"day_year": "2021-02-10", "total_view": 7},
                    {"day_year": "2021-02-10", "total_view": 4}, {"day_year": "2021-02-09", "total_view": 1},
                    {"day_year": "2021-02-17", "total_view": 1}]
            today = datetime.date.today()
            count = 0
            for i in range(len(data), 0, -1):
                day = today - relativedelta(months=i)
                data[count]['day_year'] = day.year
                data[count]['day_month'] = day.month
                count += 1
            return data

        return list(objs)


class ProductViewData(APIView):

    def get(self, request, *args, **kwargs):
        shop = request.user.get_shop()

        if request.GET.get('type') == 'month':
            data = self.get_month_data(shop)
        if request.GET.get('type') == 'by_week':
            data = self.get_data_by_week(shop)
        elif request.GET.get('type') == 'by_month':
            data = self.get_data_by_month(shop)
        else:
            data = self.get_data_by_day(shop)

        return Response(data=data, status=status.HTTP_200_OK)

    def get_month_data(self, shop):
        this_month = datetime.date.today()
        last_month = this_month - relativedelta(months=1)

        kwargs = {
            'viewed_date__month': this_month.month,
            'created_at__year': this_month.year,
        }
        this_month_count = ProductView.objects.filter(
            product__shop=shop,
            viewed_date__month=this_month.month,
            viewed_date__year=this_month.year) \
                               .aggregate(this_month_count=Sum('count'))['this_month_count'] or 0
        last_month_count = ProductView.objects.filter(product__shop=shop,
                                                      viewed_date__month=last_month.month,
                                                      viewed_date__year=last_month.year) \
                               .aggregate(last_month_count=Sum('count'))['last_month_count'] or 0

        if settings.ENABLE_DUMMY_DATA:
            return {
                'this_month': 210,
                'last_month': 110
            }

        return {
            'this_month': this_month_count,
            'last_month': last_month_count
        }

    def get_data_by_day(self, shop):
        objs = ProductView.objects.filter(
                product__shop=shop).values('viewed_date') \
            .annotate(total_view=Sum('count')) \
            .values('viewed_date', 'total_view')

        if settings.ENABLE_DUMMY_DATA:
            data = [{"viewed_date": "2021-02-11", "total_view": 5}, {"viewed_date": "2021-02-12", "total_view": 3},
                    {"viewed_date": "2021-02-10", "total_view": 6}, {"viewed_date": "2021-02-09", "total_view": 2}]
            today = datetime.date.today()
            count = 0
            for i in range(len(data), 0, -1):
                data[count]['viewed_date'] = format("Y-m-d", today - relativedelta(days=i))
                count += 1
            return data

        return list(objs)

    def get_data_by_week(self, shop):
        objs = ProductView.objects.filter(
                product__shop=shop) \
            .annotate(
                day_year=ExtractYear('viewed_date'),
                day_week=ExtractWeek('viewed_date')) \
            .values('day_year', 'day_week') \

bloom/analytics/views.py
from django.shortcuts import render

# Create your views here.

bloom/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.generics import CreateAPIView
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin, CreateModelMixin
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer, ShopperSerializer, VendorSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)


class ShopperSignUpAPIView(CreateAPIView):
    serializer_class = ShopperSerializer
    permission_classes = []


class VendorSignUpAPIView(CreateAPIView):
    serializer_class = VendorSerializer
    permission_classes = []


class SignUpInitialAPIView(APIView):
    permission_classes = []

    def get(self, request, *args, **kwargs):
        request.session['role'] = request.GET.get('role')
        return Response(status=status.HTTP_200_OK)

bloom/templates/users/connect_shopify.html
{% extends "base.html" %}
{% load static %}

{% block title %}Shopify Integration{% endblock %}

{% block content %}
  <div class="container font-14">
    <div class="mt-4 bg-white">
      <div class="row">
        <div class="col-md-3">
          {% include 'users/navbar.html' %}
        </div>
        <div class="col-sm-9">
          <h3 class="mt-3">Install app</h3>
          <div class="pr-3">
            <p>Install this app in a shop to get access to its private admin data.</p>
            <p style="padding-bottom: 1em"><span class="hint">Don&rsquo;t have a shop to install this app in handy? <a href="https://www.shopify.com/signup">Create a shop.</a></span></p>


            {% if form.non_field_errors and form.config_type.value == 'app' %}
              <div class="non-field-errors">
                {% for err in form.non_field_errors %}
                  <p class="form-error">{{ err }}</p>
                {% endfor %}
              </div>
            {% endif %}
            <form method="post" action="." @submit="handleClick()">  {% csrf_token %}
              <div class="form-group row">
                <label for="shop_url" class="col-sm-2 col-form-label font-14">Shop URL</label>
                <div class="col-6">
                  <input type="url" class="form-control font-14 {% if shopify.is_verified and shopify.config_type == 'app' %}is-valid{% endif %}" id="shop_url" required name="shop_url" value="{{ form.shop_url.value }}" placeholder="https://myshop.myshopify.com">
                  {% if shopify.is_verified and shopify.config_type == 'app' %}
                  <div class="valid-feedback">
                    <i class="fas fa-check font-16"></i> The app is installed to Shopify store
                  </div>
                  {% endif %}
                </div>
              </div>
              <div class="form-group row">
                <div class="col-6 offset-2">
                  {% if shopify.is_verified and shopify.config_type == "app" %}
                    <button class="btn btn-primary white" type="submit" v-html="loading ? 'Reinstalling...' : 'Reinstall'">Reinstall</button>
                  {% else %}
                    <button class="btn btn-primary white" type="submit" v-html="loading ? 'Installing...' : 'Install'">Install</button>
                  {% endif %}
                </div>
                <input type="hidden" name="config_type" value="app">
              </div>
            </form>
          </div>

          <a class="mt-3" href="#collapseManual" role="button" data-toggle="collapse"
             aria-expanded="{% if form.config_type.value == 'manual' or shopify.config_type == 'manual' %}true{% else %}false{% endif %}"
             aria-controls="collapseManual">Manual Setup</a>
          <div class="pr-3 collapse {% if form.config_type.value == 'manual' or shopify.config_type == 'manual' %}show{% endif %}" id="collapseManual">
            <div class="card card-body">
              <h4 class="font-14 mt-4">Provide your App credentials:</h4>

              {% if form.non_field_errors and form.config_type.value == 'manual' %}
                <div class="non-field-errors">
                  {% for err in form.non_field_errors %}
                    <p class="form-error">{{ err }}</p>
                  {% endfor %}
                </div>
              {% endif %}

              <form method="post" action=".">  {% csrf_token %}
                <div class="form-group row">
                  <label for="shop_url" class="col-sm-2 col-form-label font-14">Shop URL</label>
                  <div class="col-6">
                    <input type="url" class="form-control font-14" id="shop_url" required name="shop_url" value="{{ form.shop_url.value }}" placeholder="https://myshop.myshopify.com">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="api_key" class="col-sm-2 col-form-label font-14">API Key</label>
                  <div class="col-6">
                    <input type="text" class="form-control font-14" id="api_key" required name="api_key" placeholder="API key" value="{{ shopify.api_key }}">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="api_password" class="col-sm-2 col-form-label  font-14">Password</label>
                  <div class="col-6">
                    <input type="password" class="form-control font-14" id="api_password" required name="password" value="{{ shopify.password }}" placeholder="Password">
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-6 offset-2">
                    <button class="btn btn-primary white" type="submit">Save</button>

                    {% if shopify.config_type == 'manual' and shopify.is_verified %}
                      <span class="ml-2" style="color: #28a745;font-size: 80%">
                        <i class="fas fa-check font-16"></i> Connected to shopify Store
                      </span>
                    {% endif %}
                  </div>
                </div>
                <input type="hidden" name="config_type" value="manual">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block main_vue %}
  <script>
  let main = new Vue({
    el: '#app',
    delimiters: ["[{", "}]"],
    data: function () {
      return {
        media_url: "{{ MEDIA_URL }}",
        loading: false,
      }
    },
    methods: {
      stripe_connect() {
        let that = this;
        that.loading = true;
        this.$store.dispatch('strip_connect').then(function (res) {
          if (res.data.url) {
            window.location = res.data.url;
          }
          that.loading = false;
        }).catch(function (err) {
          console.log(err);
          alert("Oops, Something wrong!")
        })
      },
      handleClick() {
        this.loading = true;
      }
    }
  });
  </script>
{% endblock %}

bloom/templates/users/connect_stripe.html
{% extends "base.html" %}
{% load static %}

{% block title %}Stripe Integration{% endblock %}

{% block content %}
  <div class="container">
    <div class="mt-4 bg-white">
      <div class="row">
        <div class="col-md-3">
          {% include 'users/navbar.html' %}
        </div>
        <div class="col-sm-9">
          <h3 class="mt-3">Stripe Integration</h3>
          <div class="form-row align-items-center">
            {% if user.stripe_account_id %}
              <div class="col-auto my-1">
                <label><strong>Stripe Account ID</strong>: {{ user.stripe_account_id }}</label><br>
                <label><strong>Stripe Account Status</strong>: <span href="#" class="badge {% if user.charges_enabled %}badge-success{% else %}badge-warning{% endif %}">{{ user.get_charge_status }}</span></label>
              </div>
            {% else %}
              <div class="col-auto my-1">
                <button :disabled="loading" type="button" @click="stripe_connect()" class="btn btn-primary white">Connect with Stripe</button>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block main_vue %}
  <script>
  let main = new Vue({
    el: '#app',
    delimiters: ["[{", "}]"],
    data: function () {
      return {
        media_url: "{{ MEDIA_URL }}",
        loading: false,
      }
    },
    methods: {
      stripe_connect() {
        let that = this;
        that.loading = true;
        this.$store.dispatch('strip_connect').then(function (res) {
          if (res.data.url) {
            window.location = res.data.url;
          }
          that.loading = false;
        }).catch(function (err) {
          console.log(err);
          alert("Oops, Something wrong!")
        })
      }
    }
  });
  </script>
{% endblock %}

bloom/templates/users/connect_wordpress.html
{% extends "base.html" %}
{% load static %}

{% block title %}Wordpress Integration{% endblock %}

{% block content %}
  <div class="container font-14">
    <div class="mt-4 bg-white">
      <div class="row">
        <div class="col-md-3">
          {% include 'users/navbar.html' %}
        </div>
        <div class="col-sm-9">
          <h3 class="mt-3">Wordpress Integration</h3>

          <p class="mt-3">Follow <a href="https://docs.woocommerce.com/document/woocommerce-rest-api/">the document</a> how to generate your api key</p>
          <div class="pr-3">
            <h4 class="font-16 mt-4">Provide your API Key:</h4>

            {% if form.non_field_errors %}
              <div class="non-field-errors">
                {% for err in form.non_field_errors %}
                  <p class="form-error">{{ err }}</p>
                {% endfor %}
              </div>
            {% endif %}
            <form method="post" action=".">  {% csrf_token %}
              <div class="form-group row">
                <label for="shop_url" class="col-sm-2 col-form-label font-14">Shop URL</label>
                <div class="col-6">
                  <input type="url" class="form-control font-14" id="shop_url" required name="shop_url" value="{{ form.shop_url.value }}" placeholder="https://myshop.com">
                </div>
              </div>
              <div class="form-group row">
                <label for="api_key" class="col-sm-2 col-form-label font-14">API Key</label>
                <div class="col-6">
                  <input type="text" class="form-control font-14" id="api_key" required name="api_key" placeholder="API key" value="{{ form.api_key.value }}">
                </div>
              </div>
              <div class="form-group row">
                <label for="inputPassword" class="col-sm-2 col-form-label  font-14">API Secret</label>
                <div class="col-6">
                  <input type="password" class="form-control font-14" id="api_secret_key" required name="secret_key" value="{{ form.secret_key.value }}" placeholder="API secret key">
                </div>
              </div>
              <div class="form-group row">
                <div class="col-6 offset-2">
                  <button class="btn btn-primary white" type="submit">Save</button>
                  {% if shop.secret_key %}
                  <span class="ml-2" style="color: #28a745;font-size: 80%">
                    <i class="fas fa-check font-16"></i> Your key is verified.
                  </span>
                  {% endif %}
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block main_vue %}
  <script>
  let main = new Vue({
    el: '#app',
    delimiters: ["[{", "}]"],
    data: function () {
      return {
        media_url: "{{ MEDIA_URL }}",
        loading: false,
      }
    },
    methods: {
      stripe_connect() {
        let that = this;
        that.loading = true;
        this.$store.dispatch('strip_connect').then(function (res) {
          if (res.data.url) {
            window.location = res.data.url;
          }
          that.loading = false;
        }).catch(function (err) {
          console.log(err);
          alert("Oops, Something wrong!")
        })
      },
      handleClick() {
        this.loading = true;
      }
    }
  });
  </script>
{% endblock %}

bloom/templates/users/navbar.html
<ul role="menubar" class="el-menu-vertical-demo el-menu" style="height: 100%; min-height: 400px">
  <li role="menuitem" tabindex="-1" class="el-menu-item {% if page == 'profile' %}is-active{% endif %}" style="padding-left: 20px;">
    <i class="fas fa-user"></i> <a href="{% url 'users:detail' %}"><span>Your profile</span></a>
  </li>
  {% if user.role_type == '1' %}
  <li role="menuitem" tabindex="-1" class="el-menu-item {% if page == 'shop' %}is-active{% endif %}" style="padding-left: 20px;">
    <i class="fas fa-store"></i> <a href="{% url 'users:shop' %}"><span>Shop</span></a>
  </li>
  <li role="menuitem" tabindex="-1" class="el-menu-item {% if page == 'stripe' %}is-active{% endif %}" style="padding-left: 20px;">
    <i class="fab fa-stripe-s"></i> <a href="{% url 'users:stripe-integration' %}"><span>Stripe integration</span></a>
  </li>
  <li role="menuitem" tabindex="-1" class="el-menu-item {% if page == 'shopify' %}is-active{% endif %}" style="padding-left: 20px;">
    <i class="fab fa-shopify"></i> <a href="{% url 'users:shopify-integration' %}"><span>Shopify integration</span></a>
  </li>
  <li role="menuitem" tabindex="-1" class="el-menu-item {% if page == 'wordpress' %}is-active{% endif %}" style="padding-left: 20px;">
    <i class="fab fa-wordpress"></i> <a href="{% url 'users:wordpress-integration' %}"><span>Wordpress integration</span></a>
  </li>
  {% endif %}
</ul>

bloom/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <div class="container">
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="control-group">
        <div class="controls">
          <button type="submit" class="btn btn-primary">Update</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}